<?php

namespace AppBundle\Repository;

/**
 * PacienteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PacienteRepository extends \Doctrine\ORM\EntityRepository
{

    public function totalPacientes()
    {
        $total = $this->getEntityManager()
            ->createQuery('SELECT COUNT(p.id) FROM AppBundle:Paciente p')
            ->getResult();

        return $total[0][1];
        //var_dump($total); Para ver que viene en la variable.
    }

    public function updateFonetico()
    {
        $localizar = $this->getEntityManager()
            ->createQuery('SELECT p FROM AppBundle:Paciente p WHERE p.fonNombre is null ')
            ->getResult();

        return $localizar;

    }
}
